apiVersion: v1
kind: Service
metadata:
  name: ms-peliculas-backend
  labels:
    app: ms-peliculas-backend
spec:
  type: NodePort
  selector:
    app: ms-peliculas-backend
  ports:
  - protocol: TCP
    port: 9080
    targetPort: 9080
    nodePort: 30080